### PR TITLE
Remove requests for non-offering driver

### LINKED ISSUE #192: Remove requests for non-offering driver
I made a request with username1. I logged in and made requests as username2, username3, username4, and username5. I logged back in as username1 and confirmed username2 as my driver. I logged back into username3, and I am still able to see the request. The status is "confirmed" and I can see username2 as the driver for the request. Since I, as username3, am no longer involved in the request it seems weird (and a possible privacy breach) that I can still see the request even though I am no longer involved in it. I would consider this something that we should fix before the end of Part 5. I also see all the updates in the status which feels kind of creepy.

### PR DESCRIPTION
**Pull request by MichaelParadis**
Fixes the issue by removing all offers and adding a new offer. Addresses #192.

### CODE REVIEW

**Comment by Hreherch** [comment]
Why re-add the driver?
We should probably be checking for "chosen" drivers in the getOfferedRequests task.

**Comment by Hreherch** [comment]
Why re-add the driver?
We should probably be checking for "chosen" drivers in the getOfferedRequests task.

**Comment by MichaelParadis** [comment]
@Hreherch  I address this concern in the latest commit.

**Comment by Hreherch** [comment]
You didn't need to make two queries, I believe. 

Check out the "bool": [ ... ] and "minimum_should_match" operator for elastic search.

**Comment by kieter** [comment]
This works.

**Pull request merged**
