### PR TITLE
Map improvements

### PR DESCRIPTION
**Pull request by sehoven**
Solves [#104](https://github.com/CMPUT301F16T01/Carrier/issues/104).

Start and end markers changed, dynamic zoom for map views.

### CODE REVIEW

**Review by MandyMeindersma — COMMENTED** [review]
Everything is commented beautifully. This all looks amazing. They only thing I have a question about is that you write down the "getBoundingBox" function 3 times. Should we write this once somewhere else and then just call it? or is that too much work?

**Review by MandyMeindersma — CHANGES_REQUESTED** [review]
thoughts?

**Comment by sehoven** [comment]
I realize that there is some code duplication here that could be made simpler. To do that we would need to do a lot of restructuring work so in the interest of time, I was ignoring it. Honestly if we had more time there is a lot of code reduplication between the Driver and Rider view location activities that could be resolved, but I would say that this is possibly something for Part 6.

**Comment by MandyMeindersma** [comment]
Completely understandable. You did a great job

**Review by MandyMeindersma — APPROVED** [review]

**Pull request merged**
